name: Build

on:
  push:
    branches: [main, master]
    paths-ignore:
      - README.md
      - scalafmt.conf

  pull_request:
    branches: [main, master]
    paths-ignore:
      - README.md
      - scalafmt.conf

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-scala
          path: |
            ~/.ivy2/cache
            ~/.sbt
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "adopt"
      - name: Compile and run tests
        run: sbt "test"
